# This .travis.yml on:
# https://github.com/loot/loot/blob/dev/.travis.yml
# https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/?

language: cpp
dist: trusty

cache:
  directories:
    - $HOME/.ccache

addons:
  apt:
    update: true
    packages: &default_packages
      - libgsl0ldbl
      - libgsl0-dev
    sources: &default_sources
      - ubuntu-toolchain-r-test
    packages: &default_packages
#      # - libhdf5-dev

matrix:
  include:

    - os: linux
      compiler: gcc
      env: CXX_NAME='g++-6'
      addons: {apt: { packages: [*default_packages, g++-6], sources: [*default_sources]}}

    - os: linux
      compiler: gcc
      env: CXX_NAME='g++-6' CMAKE_BUILD_TYPE=Debug
      addons: {apt: { packages: [*default_packages, g++-6], sources: [*default_sources]}}

    - os: linux
      compiler: gcc
      env: CXX_NAME='g++-7'
      addons: {apt: { packages: [*default_packages, g++-7], sources: [*default_sources]}}

    - os: linux
      compiler: clang
      env: CXX_NAME='clang++-6.0'
      addons: {apt: { packages: [*default_packages, clang-6.0], sources: [*default_sources, llvm-toolchain-trusty-6.0]}}

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: CXX_NAME='c++'

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: CXX_NAME='c++'

    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env: CXX_NAME='clang++'

before_install:
  # Check commit matches expected commit (because of Travis bug)
  - if [[ "$TRAVIS_COMMIT" != "$(git rev-parse HEAD)" ]]; then echo "Commit doesn't match expected $TRAVIS_COMMIT"; fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CXX_NAME" == "clang++" ]]; then
      brew install --with-clang llvm@6
      brew link --force --overwrite llvm@6
      brew install gsl
    fi
  # This is required to override Travis's definitions of CC and CXX that lead to old Ubuntu-packaged compilers
  - export CXX="$CXX_NAME"

#install:
    #--------- OSX
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew upgrade cmake
      brew install ccache
    fi

script:
  - mkdir build && cd build && cmake .. && make

