#ifndef SIMPACT_CYAN_VERSION_H

#define SIMPACT_CYAN_VERSION_H

//#define SIMPACT_CYAN_VERSION	"${VERSION}"
//#define SIMPACT_CYAN_COMPILER	"${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}"

#define SIMPACT_CYAN_VERSION	"hack"
#define SIMPACT_CYAN_COMPILER	"hack"

#endif // SIMPACT_CYAN_VERSION_H
